Attribute VB_Name = "RAJ_HM"
Option Explicit

Public Function Select_Raj_Hm(Raj_Kod As String)
Select Case Raj_Kod
    Case "01"
        Select_Raj_Hm = "Білогірський район"
    Case "02"
        Select_Raj_Hm = "Віньковецький район"
    Case "03"
        Select_Raj_Hm = "Волочиський район"
    Case "04"
        Select_Raj_Hm = "Городоцький район"
    Case "05"
        Select_Raj_Hm = "Деражнянський район"
    Case "06"
        Select_Raj_Hm = "Дунаєвецький район"
    Case "07"
        Select_Raj_Hm = "Ізяславський район"
    Case "08"
        Select_Raj_Hm = "Кам`янець-Подiльський район"
    Case "09"
        Select_Raj_Hm = "Красилiвський район"
    Case "10"
        Select_Raj_Hm = "Летичiвський район"
    Case "11"
        Select_Raj_Hm = "Новоушицький район"
    Case "12"
        Select_Raj_Hm = "Полонський район"
    Case "13"
        Select_Raj_Hm = "Старокостянтинiвський район"
    Case "14"
        Select_Raj_Hm = "Старосинявський район"
    Case "15"
        Select_Raj_Hm = "Теофiпольський район"
    Case "16"
        Select_Raj_Hm = "Хмельницький район"
    Case "17"
        Select_Raj_Hm = "Чемеровецький район"
    Case "18"
        Select_Raj_Hm = "Шепетiвський район"
    Case "19"
        Select_Raj_Hm = "Ярмолинецький район"
    Case "20"
        Select_Raj_Hm = "м.Хмельницький - 20"
    Case "21"
        Select_Raj_Hm = "м.Кам`янцi-Подiльський район"
    Case "23"
        Select_Raj_Hm = "Славутський район та м.Славута"
    Case "24"
        Select_Raj_Hm = "м.Нетiшин"
    Case "25"
        Select_Raj_Hm = "м.Хмельницький"
    Case "26"
        Select_Raj_Hm = "м.Шепетiвка"
End Select
    
End Function
